require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*
    - db/**/*.rb
    - node_modules/**/*
    - output/**/*
    - vendor/**/*
  TargetRubyVersion: 2.7.1
  RSpec:
    Patterns:
      - _spec.rb
      - "(?:^|/)spec/"
    SpecTypes:
      Feature: 'spec/features/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true
