plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - bin/*
    - db/**/*.rb
    - node_modules/**/*
    - output/**/*
    - vendor/**/*
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/EmptyLineBetweenDefs:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/Output:
  Enabled: false
